export const ASSET_TUNING = {
  "jack.idle.N": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.NE": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.E": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.SE": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.S": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.SW": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.W": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.idle.NW": { drawScale: 1.02, drawOffsetY: 2 },
  "jack.run.N": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.NE": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.E": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.SE": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.S": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.SW": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.W": { drawScale: 1.04, drawOffsetY: 2 },
  "jack.run.NW": { drawScale: 1.04, drawOffsetY: 2 },
  "lifeform.plant": { drawScale: 1.05 },
  "lifeform.animal": { drawScale: 1.06 },
  "lifeform.bacteria": { drawScale: 1.08 },
  "lifeform.virus": { drawScale: 1.08 },
  "lifeform.fungus": { drawScale: 1.1 },
  "lifeform.alien": { drawScale: 1.12 },
  "pickup.weapon_bleach": { drawScale: 0.9 },
  "pickup.weapon_flame": { drawScale: 0.9 },
  "pickup.tank_bleach": { drawScale: 0.95 },
  "pickup.tank_fuel": { drawScale: 0.95 },
  "pickup.sugar_cube": { drawScale: 0.9 },
  "effect.bleach_puddle": { drawScale: 1.0 },
  "effect.flame_cone": { anchorX: 0.02, anchorY: 0.5, drawScale: 1.12, drawOffsetX: 0 },
  "effect.fungal_mat": { drawScale: 1.05 },
  "effect.alien_tendril_tip": { drawScale: 1.0 }
};
